import { EventEmitter } from "../../stencil-public-runtime";
export declare class CcTextarea {
    private richTextEl?;
    private textAreaEl?;
    private editorInstance;
    lengthCharacter: Number;
    color: "primary" | "secondary";
    label?: string;
    error?: boolean;
    success?: boolean;
    disabled?: boolean;
    placeholder?: string;
    name?: string;
    rich?: boolean;
    value?: string;
    iconName?: string;
    helperText?: string;
    maxLength?: number;
    outlined: boolean;
    autoGrow?: boolean;
    withoutRadius?: boolean;
    counter?: boolean;
    bgField?: "transparent" | "white";
    toolbar?: string[];
    enableImage?: boolean;
    imageService?: (file: any) => Promise<string>;
    enableMediaEmbed?: boolean;
    focusTextEditor(): Promise<void>;
    setDataRichEditor(data: string): Promise<void>;
    validateName(newDisabled: boolean): void;
    toggleRichText(richNew: boolean, richOld: boolean): void;
    getAmountOfCharacters(): number;
    setValue(newValue: string): void;
    changeText: EventEmitter<string>;
    changeTextHandler(newText: string): void;
    setRichTextEditorDefaults(): void;
    enableRichTextEditor(): Promise<any>;
    setAdapterUpload(editor: any): void;
    disableRichTextEditor(): void;
    putCursorAtTheEnd(): void;
    focusEditor: () => void;
    componentDidLoad(): void;
    componentWillLoad(): void;
    componentDidUnload(): void;
    render(): any;
}
